<a href="https://colab.research.google.com/github/kosei-s/MachineLearningPractice/blob/master/chainer_tutorial/chainer_tutorial_note3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# ベクトルの定義
a = np.array([1, 2, 3])

a

array([1, 2, 3])

In [0]:
type(a)

numpy.ndarray

In [0]:
a.shape

(3,)

In [0]:
a.ndim

1

In [0]:
# 行列の定義
b = np.array(
      [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]
)

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
print('Shape: ', b.shape)
print('Rank: ', b.ndim)

Shape:  (3, 3)
Rank:  2


In [0]:
b.size

9

In [0]:
a = np.zeros((3, 3))

a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
b = np.ones((2, 3))

b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [0]:
c = np.full((3, 2), 9)

c

array([[9, 9],
       [9, 9],
       [9, 9]])

In [0]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
e = np.random.random((4, 5))
e

array([[0.77612638, 0.82421479, 0.08438491, 0.74021835, 0.41467918],
       [0.96322256, 0.03121534, 0.34447072, 0.87144098, 0.17764711],
       [0.04203459, 0.80359595, 0.80120201, 0.63048613, 0.60593958],
       [0.89227104, 0.06014315, 0.39367488, 0.99194311, 0.07454967]])

In [0]:
f = np.arange(3, 10, 1)
f

array([3, 4, 5, 6, 7, 8, 9])

In [0]:
val = e[0, 1]
val

0.8242147852350307

In [0]:
center = e[1:3, 1:4]
center

array([[0.03121534, 0.34447072, 0.87144098],
       [0.80359595, 0.80120201, 0.63048613]])

In [0]:
print('Shape of e: ', e.shape)
print('Shape of center: ', center.shape)

Shape of e:  (4, 5)
Shape of center:  (2, 3)


In [0]:
e[1:3, 1:4] = 0
e

array([[0.77612638, 0.82421479, 0.08438491, 0.74021835, 0.41467918],
       [0.96322256, 0.        , 0.        , 0.        , 0.17764711],
       [0.04203459, 0.        , 0.        , 0.        , 0.60593958],
       [0.89227104, 0.06014315, 0.39367488, 0.99194311, 0.07454967]])

In [0]:
a = np.array(
      [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]
)

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.array([a[0, 1], a[2, 1], a[1, 0]])

array([2, 8, 4])

In [0]:
a[[0, 2, 1], [1, 1, 0]]

array([2, 8, 4])

In [0]:
x = np.array([1, 2, 3])

x.dtype

dtype('int64')

In [0]:
x = np.array([1., 2., 3.])

x.dtype

dtype('float64')

In [0]:
x = np.array([1, 2, 3], dtype='float32')

x.dtype

dtype('float32')

In [0]:
x = np.array([1, 2, 3], dtype='f')

x.dtype

dtype('float32')

In [0]:
x = x.astype('float64')

x.dtype

dtype('float64')

In [0]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [0]:
c = a + b

c

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [0]:
c = a - b

c

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [0]:
c = a * b

c

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [0]:
c = a / b

c

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [0]:
c = np.sqrt(b)

c

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [0]:
n = 2
c = np.power(b, n)

c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [0]:
c ** n

array([[   1,   16,   81],
       [ 256,  625, 1296],
       [2401, 4096, 6561]])

In [0]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

b = np.array([1, 2, 3])

c = a + b

c

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [0]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [0]:
b = np.array([2, 2, 2])
c = a * b
c

array([2, 4, 6])

In [0]:
c = a * 2
c

array([2, 4, 6])

In [0]:
a = np.array([
    [0, 1, 2, 1, 0],
    [3, 4, 5, 4, 3],
    [6, 7, 8, 7, 6],
    [3, 4, 5, 4, 4],
    [0, 1, 2, 1, 0]
])

b = np.array([1, 2, 3, 4, 5])

c = np.empty((5, 5))

In [0]:
%%timeit
for i in range(a.shape[0]):
  c[i, :] = a[i, :] + b

The slowest run took 12.57 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 6.68 µs per loop


In [0]:
c

array([[ 1.,  3.,  5.,  5.,  5.],
       [ 4.,  6.,  8.,  8.,  8.],
       [ 7.,  9., 11., 11., 11.],
       [ 4.,  6.,  8.,  8.,  9.],
       [ 1.,  3.,  5.,  5.,  5.]])

In [0]:
%%timeit
c = a + b

The slowest run took 41.29 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.13 µs per loop


In [0]:
c

array([[ 1.,  3.,  5.,  5.,  5.],
       [ 4.,  6.,  8.,  8.,  8.],
       [ 7.,  9., 11., 11., 11.],
       [ 4.,  6.,  8.,  8.,  9.],
       [ 1.,  3.,  5.,  5.,  5.]])

In [0]:
# 行列 A の定義
A = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

# 行列 B の定義
B = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [0]:
C = np.dot(A, B)
C

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [0]:
C = A.dot(B)
C

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [0]:
x = np.random.randint(0, 10, (8, 10))
x

array([[5, 6, 0, 5, 5, 2, 3, 1, 4, 1],
       [7, 0, 8, 9, 8, 8, 8, 8, 6, 4],
       [1, 6, 4, 8, 5, 9, 7, 5, 2, 9],
       [0, 4, 8, 6, 5, 5, 7, 5, 4, 9],
       [8, 3, 1, 6, 2, 3, 8, 9, 2, 9],
       [9, 9, 8, 1, 0, 8, 7, 6, 0, 0],
       [2, 4, 3, 7, 6, 1, 3, 0, 7, 1],
       [4, 1, 9, 1, 2, 0, 7, 7, 3, 4]])

In [0]:
x.mean()

4.725

In [0]:
x.var()

8.824375

In [0]:
x.std()

2.9705849592294107

In [0]:
x.max()

9

In [0]:
x.min()

0

In [0]:
x.mean(axis=1)

array([3.2, 6.6, 5.6, 5.3, 5.1, 4.8, 3.4, 3.8])

In [0]:
import numpy as np

X = np.array([
    [2, 3],
    [2, 5],
    [3, 4],
    [5, 9],
])

X

array([[2, 3],
       [2, 5],
       [3, 4],
       [5, 9]])

In [0]:
ones = np.ones((X.shape[0], 1))
X = np.concatenate((ones, X), axis=1)
X

array([[1., 2., 3.],
       [1., 2., 5.],
       [1., 3., 4.],
       [1., 5., 9.]])

In [0]:
t = np.array([1, 5, 6, 8])
t

array([1, 5, 6, 8])

In [0]:
xx = np.dot(X.T, X)
xx

array([[  4.,  12.,  21.],
       [ 12.,  42.,  73.],
       [ 21.,  73., 131.]])

In [0]:
xx_inv = np.linalg.inv(xx)
xx_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [0]:
xt = np.dot(X.T, t)
xt

array([ 20.,  70., 124.])

In [0]:
w = np.dot(xx_inv, xt)
w

array([-0.14285714,  0.71428571,  0.57142857])

In [0]:
w_ = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(t)
w_

array([-0.14285714,  0.71428571,  0.57142857])

In [0]:
w_ = np.linalg.solve(X.T.dot(X), X.T.dot(t))
w_

array([-0.14285714,  0.71428571,  0.57142857])