<a href="https://colab.research.google.com/github/kosei-s/MachineLearningPractice/blob/master/chainer_tutorial/chainer_tutorial_note4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.datasets import load_boston

dataset = load_boston()

In [0]:
type(dataset)

sklearn.utils.Bunch

In [0]:
x = dataset.data
t = dataset.target

In [0]:
x.shape

(506, 13)

In [0]:
t.shape

(506,)

In [0]:
from sklearn.model_selection import train_test_split

x_train, x_test, t_train, t_test = train_test_split(x, t, test_size=0.3, random_state= 0)

In [0]:
from sklearn.linear_model import LinearRegression

reg_model = LinearRegression()

In [0]:
reg_model.fit(x_train, t_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
# w
reg_model.coef_

array([-1.21310401e-01,  4.44664254e-02,  1.13416945e-02,  2.51124642e+00,
       -1.62312529e+01,  3.85906801e+00, -9.98516565e-03, -1.50026956e+00,
        2.42143466e-01, -1.10716124e-02, -1.01775264e+00,  6.81446545e-03,
       -4.86738066e-01])

In [0]:
# b
reg_model.intercept_

37.93710774183309

In [0]:
reg_model.score(x_train, t_train)

0.7645451026942549

In [0]:
reg_model.predict(x_test[:1])

array([24.9357079])

In [0]:
t_test[0]

22.6

In [0]:
reg_model.score(x_test, t_test)

0.6733825506400171

In [0]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [0]:
scaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [0]:
scaler.mean_

array([3.35828432e+00, 1.18093220e+01, 1.10787571e+01, 6.49717514e-02,
       5.56098305e-01, 6.30842655e+00, 6.89940678e+01, 3.76245876e+00,
       9.35310734e+00, 4.01782486e+02, 1.84734463e+01, 3.60601186e+02,
       1.24406497e+01])

In [0]:
scaler.var_

array([6.95792305e+01, 5.57886665e+02, 4.87753572e+01, 6.07504229e-02,
       1.33257561e-02, 4.91423928e-01, 7.83932705e+02, 4.26314655e+00,
       7.49911344e+01, 2.90195600e+04, 4.93579208e+00, 7.31040807e+03,
       4.99634123e+01])

In [0]:
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [0]:
reg_model = LinearRegression()
reg_model.fit(x_train_scaled, t_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
reg_model.score(x_train_scaled, t_train)

0.7645451026942549

In [0]:
reg_model.score(x_test_scaled, t_test)

0.6733825506400195

In [0]:
from sklearn.preprocessing import PowerTransformer

scaler = PowerTransformer()
scaler.fit(x_train)

x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

reg_model = LinearRegression()
reg_model.fit(x_train_scaled, t_train)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:2863: RuntimeWarning: divide by zero encountered in log
  loglike = -n_samples / 2 * np.log(x_trans.var())


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
reg_model.score(x_train_scaled, t_train)

0.7859862563286062

In [0]:
reg_model.score(x_test_scaled, t_test)

0.7002856551689581

In [0]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('scaler', PowerTransformer()),
    ('reg', LinearRegression())
])

In [0]:
pipeline.fit(x_train, t_train)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:2863: RuntimeWarning: divide by zero encountered in log
  loglike = -n_samples / 2 * np.log(x_trans.var())


Pipeline(memory=None,
         steps=[('scaler',
                 PowerTransformer(copy=True, method='yeo-johnson',
                                  standardize=True)),
                ('reg',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [0]:
pipeline.score(x_train, t_train)

0.7859862563286062

In [0]:
linear_result = pipeline.score(x_test, t_test)
linear_result

0.7002856551689581